version: '3.7'
services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
    container_name: docker_test_web
  php:
    image: nanoninja/php-fpm:7.4.4
    restart: always
    volumes:
        - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./web:/var/www/html"
    container_name: docker_test_php
